/*
 * OpenSource Issue Träcking System
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: DevBoxFanBoy@github.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	opists "github.com/DevBoxFanBoy/opists/src"
)

func main() {
	log.Printf("Server started")

	IssuesApiService := opists.NewIssuesApiService()
	IssuesApiController := opists.NewIssuesApiController(IssuesApiService)

	ProjectsApiService := opists.NewProjectsApiService()
	ProjectsApiController := opists.NewProjectsApiController(ProjectsApiService)

	router := opists.NewRouter(IssuesApiController, ProjectsApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
