/*
 * OpenSource Issue Träcking System
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: DevBoxFanBoy@github.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ErrorResponse - The general Error Response.
type ErrorResponse struct {
	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`
}
