/*
 * OpenSource Issue Träcking System
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: DevBoxFanBoy@github.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

import (
	"github.com/DevBoxFanBoy/opists/pkg/api/v1/model"
	"net/http"
)

// IssuesApiRouter defines the required methods for binding the api requests to a responses for the IssuesApi
// The IssuesApiRouter implementation should parse necessary information from the http request,
// pass the data to a IssuesApiServicer to perform the required actions, then write the service results to the http response.
type IssuesApiRouter interface {
	AddIssue(http.ResponseWriter, *http.Request)
	DeleteIssue(http.ResponseWriter, *http.Request)
	GetIssueById(http.ResponseWriter, *http.Request)
	GetProjectIssues(http.ResponseWriter, *http.Request)
	UpdateIssue(http.ResponseWriter, *http.Request)
}

// ProjectsApiRouter defines the required methods for binding the api requests to a responses for the ProjectsApi
// The ProjectsApiRouter implementation should parse necessary information from the http request,
// pass the data to a ProjectsApiServicer to perform the required actions, then write the service results to the http response.
type ProjectsApiRouter interface {
	GetAllProject(http.ResponseWriter, *http.Request)
	GetProject(http.ResponseWriter, *http.Request)
}

// IssuesApiServicer defines the api actions for the IssuesApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type IssuesApiServicer interface {
	AddIssue(string, model.Issue) (interface{}, error)
	DeleteIssue(string, int64) (interface{}, error)
	GetIssueById(string, int64) (interface{}, error)
	GetProjectIssues(string) (interface{}, error)
	UpdateIssue(string, model.Issue) (interface{}, error)
}

// ProjectsApiServicer defines the api actions for the ProjectsApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ProjectsApiServicer interface {
	GetAllProject() (interface{}, error)
	GetProject(string) (interface{}, error)
}
