/*
 * OpenSource Issue Träcking System
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: DevBoxFanBoy@github.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/DevBoxFanBoy/opists/pkg/api/server"
	"github.com/DevBoxFanBoy/opists/pkg/config"
	"github.com/ilyakaznacheev/cleanenv"
	"log"
	"os"
)

func main() {
	var cfg config.Config
	err := cleanenv.ReadConfig("config.yml", &cfg)
	if err != nil {
		log.Printf("Server config error: %s", err)
		os.Exit(1)
	}
	log.Printf("Server started")
	server.NewIssueTrackingSystemServer(cfg)
}
