/*
 * OpenSource Issue Träcking System
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: DevBoxFanBoy@github.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/DevBoxFanBoy/opists/pkg/api/server"
	"log"
)

func main() {
	log.Printf("Server started")
	server.NewIssueTrackingSystemServer()
}
