CREATE TABLE IF NOT EXISTS opistsschema.casbin_rule
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    version INTEGER      NOT NULL,
    ptype   VARCHAR(255) NOT NULL,
    v0      VARCHAR(255),
    v1      VARCHAR(255),
    v2      VARCHAR(255),
    v3      VARCHAR(255),
    v4      VARCHAR(255),
    v5      VARCHAR(255),
    constraint casbin_rule_p
        primary key (id)
);

CREATE INDEX IF NOT EXISTS casbin_rule_ptype_index ON opistsschema.casbin_rule (ptype);
