/*
 * OpenSource Issue Träcking System
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: DevBoxFanBoy@github.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opists

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A ProjectsApiController binds http requests to an api service and writes the service results to the http response
type ProjectsApiController struct {
	service ProjectsApiServicer
}

// NewProjectsApiController creates a default api controller
func NewProjectsApiController(s ProjectsApiServicer) Router {
	return &ProjectsApiController{service: s}
}

// Routes returns all of the api route for the ProjectsApiController
func (c *ProjectsApiController) Routes() Routes {
	return Routes{
		{
			"GetAllProject",
			strings.ToUpper("Get"),
			"/v1/projects",
			c.GetAllProject,
		},
		{
			"GetProject",
			strings.ToUpper("Get"),
			"/v1/projects/{projectKey}",
			c.GetProject,
		},
	}
}

// GetAllProject - Returns all projects
func (c *ProjectsApiController) GetAllProject(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetAllProject()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetProject - Returns the Project by key
func (c *ProjectsApiController) GetProject(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	projectKey := params["projectKey"]
	result, err := c.service.GetProject(projectKey)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
