/*
 * OpenSource Issue Träcking System
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: DevBoxFanBoy@github.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opists

type Issue struct {
	Id int64 `json:"id,omitempty"`

	Name string `json:"name"`

	// Issue description Text.
	Description string `json:"description"`

	// Issue status.
	Status string `json:"status,omitempty"`

	// Issue priority.
	Priority string `json:"priority"`

	ProjectKey string `json:"projectKey"`

	Components []string `json:"components,omitempty"`

	Sprints []string `json:"sprints,omitempty"`

	// Issue estimated points of complexity.
	EstimatedPoints int32 `json:"estimatedPoints,omitempty"`

	// Issue estimated time until resolved.
	EstimatedTime string `json:"estimatedTime,omitempty"`

	// Issue affects software version.
	AffectedVersion string `json:"affectedVersion,omitempty"`

	// Software version that fix this issue.
	FixedVersion string `json:"fixedVersion,omitempty"`
}
