/*
 * OpenSource Issue Träcking System
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: DevBoxFanBoy@github.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opists

type Component struct {
	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	Versions []string `json:"versions,omitempty"`
}
