/*
 * OpenSource Issue Träcking System
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: DevBoxFanBoy@github.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package issues

import (
	"errors"
	"github.com/DevBoxFanBoy/opists/pkg/api/v1"
	"github.com/DevBoxFanBoy/opists/pkg/api/v1/model"
)

// IssuesApiService is a service that implents the logic for the IssuesApiServicer
// This service should implement the business logic for every endpoint for the IssuesApi API.
// Include any external packages or services that will be required by this service.
type ApiService struct {
}

// NewApiService creates a default api service
func NewApiService() v1.IssuesApiServicer {
	return &ApiService{}
}

// AddIssue - Add a new issue to the tracking system
func (s *ApiService) AddIssue(projectKey string, body model.Issue) (interface{}, error) {
	// TODO - update AddIssue with the required logic for this service method.
	// Add api_issues_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'AddIssue' not implemented")
}

// DeleteIssue - Deletes a Issue
func (s *ApiService) DeleteIssue(projectKey string, id int64) (interface{}, error) {
	// TODO - update DeleteIssue with the required logic for this service method.
	// Add api_issues_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DeleteIssue' not implemented")
}

// GetIssueById - Find Issue by ID
func (s *ApiService) GetIssueById(projectKey string, id int64) (interface{}, error) {
	// TODO - update GetIssueById with the required logic for this service method.
	// Add api_issues_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetIssueById' not implemented")
}

// GetProjectIssues - Returns all Issues of the Project.
func (s *ApiService) GetProjectIssues(projectKey string) (interface{}, error) {
	// TODO - update GetProjectIssues with the required logic for this service method.
	// Add api_issues_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetProjectIssues' not implemented")
}

// UpdateIssue - Update an existing issue
func (s *ApiService) UpdateIssue(projectKey string, body model.Issue) (interface{}, error) {
	// TODO - update UpdateIssue with the required logic for this service method.
	// Add api_issues_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'UpdateIssue' not implemented")
}
